from enum import Enum


class OrderState(str, Enum):
    PAYMENT_SUCCESS_RECEIVED = "PAYMENT_SUCCESS_RECEIVED"
    RESTAURANT_TRIGGERED = "RESTAURANT_TRIGGERED"
    DISPATCH_TRIGGERED = "DISPATCH_TRIGGERED"
    RIDER_ASSIGNED = "RIDER_ASSIGNED"
    PARTIALLY_FAILED = "PARTIALLY_FAILED"
    FAILED = "FAILED"
